"""update_carowner_table

Revision ID: 3126c69cc326
Revises: 864a6299f06c
Create Date: 2024-01-09 11:27:27.834954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3126c69cc326'
down_revision = '864a6299f06c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carowners', sa.Column('showroom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carowners', 'showrooms', ['showroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carowners', type_='foreignkey')
    op.drop_column('carowners', 'showroom_id')
    # ### end Alembic commands ###
