"""create_cars_table

Revision ID: 864a6299f06c
Revises: d2a1cae7900f
Create Date: 2024-01-09 08:39:58.227871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864a6299f06c'
down_revision = 'd2a1cae7900f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=True),
    sa.Column('car_cc', sa.Integer(), nullable=True),
    sa.Column('showroom_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['carowners.id'], ),
    sa.ForeignKeyConstraint(['showroom_id'], ['showrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
